name: modul5
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  appwrite: ^12.0.3
  country_code_picker: ^3.0.0
  file_picker: ^8.0.3
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  http: ^1.2.1
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^1.1.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

